// THE SIX live draft engine. Admin-gated drafting, configurable timer, captain-only picks, reserve rules.
const HOST_CODE='1290';
const TEAM_CODES={T01:'SIX-T01-DEMO',T02:'SIX-T02-DEMO',T03:'SIX-T03-FAY',T04:'SIX-T04-DEMO',T05:'SIX-T05-DEMO',T06:'SIX-T06-DEMO'};
const ROLES=['ALL','VANGUARD','DUELIST','STRATEGIST','FLEX'];
const players=Array.from({length:24},(_,i)=>({id:`P${String(i+1).padStart(3,'0')}`,name:i===0?'GRIMM':`PLAYER ${String(i+1).padStart(2,'0')}`,role:['VANGUARD','DUELIST','STRATEGIST','FLEX'][i%4],card:i===0?'cards/P001.svg':'cards/player-placeholder.svg'}));
const makeTeam=id=>({id,name:`TEAM ${String(id).padStart(2,'0')}`,captain:`CAPTAIN ${String(id).padStart(2,'0')}`,roster:[]});
let state={mode:'broadcast',adminAuthed:false,captainTeam:null,teamsCount:4,clockSetting:60,round:0,pickIndex:0,started:false,paused:true,remaining:60,deadline:null,target:null,broadcastReveal:null,privateReveals:{},reserved:{},reserveMeta:{},drafted:{},filter:'ALL',teams:Array.from({length:6},(_,i)=>makeTeam(i+1))};
const $=s=>document.querySelector(s),app=$('#app');
const activeTeams=()=>state.teams.slice(0,state.teamsCount),team=id=>state.teams.find(t=>t.id===id),player=id=>players.find(p=>p.id===id);
function normalRoundOrder(round){const ids=activeTeams().map(t=>t.id);return ids.map((_,i)=>ids[(round+i)%ids.length]);}
function roundOrder(round){let ord=normalRoundOrder(round);const comps=activeTeams().filter(t=>state.reserveMeta[t.id]?.compRound===round).map(t=>t.id);for(const tid of comps){ord=ord.filter(x=>x!==tid);ord.push(tid);}const skipped=new Set(activeTeams().filter(t=>state.reserveMeta[t.id]?.skipRound===round).map(t=>t.id));return ord.filter(tid=>!skipped.has(tid));}
const order=()=>roundOrder(state.round),currentTeamId=()=>order()[state.pickIndex]||activeTeams()[0].id,currentTeam=()=>team(currentTeamId());
const draftedIds=()=>new Set(Object.values(state.drafted).flat()),reservedIds=()=>new Set(Object.keys(state.reserved));
const allAvailable=()=>players.filter(p=>!draftedIds().has(p.id)&&!reservedIds().has(p.id));
const fmt=s=>`00:${String(Math.max(0,s)).padStart(2,'0')}`;
const authorizedToDraft=()=>state.mode==='admin'&&state.adminAuthed||state.mode==='captain'&&state.captainTeam===currentTeamId();
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
function openModal(html){const b=document.createElement('div');b.className='modalBack';b.id='modalBack';b.innerHTML=`<div class="modal">${html}</div>`;document.body.appendChild(b)}
function closeModal(){document.getElementById('modalBack')?.remove()}
function openAdminAuth(){openModal(`<div class="eyebrow">PRIVATE ADMIN ACCESS</div><h3>ADMIN CONTROL</h3><p class="sub">Host controls remain hidden until the private admin code is entered.</p><div class="field"><label>ACCESS CODE</label><input id="adminCode" class="input" inputmode="numeric" placeholder="Enter access code"></div><div class="modalActions"><button class="btn" id="cancel">CANCEL</button><button class="btn primary" id="unlock">UNLOCK ADMIN</button></div>`);$('#cancel').onclick=closeModal;$('#unlock').onclick=()=>{if($('#adminCode').value.trim()===HOST_CODE){state.adminAuthed=true;state.mode='admin';closeModal();render();toast('Admin control unlocked.')}else toast('Invalid admin access code.')}}
function openCaptainLogin(){openModal(`<div class="eyebrow">CAPTAIN ACCESS</div><h3>ENTER TEAM CREDENTIALS</h3><div class="settingsGrid"><div class="field"><label>TEAM</label><select id="teamCode" class="select">${activeTeams().map(t=>`<option value="T${String(t.id).padStart(2,'0')}">TEAM ${String(t.id).padStart(2,'0')}</option>`).join('')}</select></div><div class="field"><label>ACCESS CODE</label><input id="capCode" class="input" placeholder="SIX-T03-FAY"></div></div><div class="modalActions"><button class="btn" id="cancel">CANCEL</button><button class="btn primary" id="enter">ENTER CAPTAIN CONTROL</button></div>`);$('#cancel').onclick=closeModal;$('#enter').onclick=()=>{const code=$('#teamCode').value,typed=$('#capCode').value.trim().toUpperCase();if(TEAM_CODES[code]===typed){state.captainTeam=Number(code.slice(1));state.mode='captain';closeModal();render()}else toast('Invalid captain credentials.')}}
function startDraft(){if(!state.adminAuthed||state.mode!=='admin')return toast('Unlock Admin Control first.');state.started=true;state.paused=false;state.round=0;state.pickIndex=0;state.target=null;state.broadcastReveal=null;state.privateReveals={};state.reserved={};state.reserveMeta={};state.drafted={};state.teams.forEach(t=>t.roster=[]);state.remaining=state.clockSetting;state.deadline=Date.now()+state.clockSetting*1000;render();toast(`Draft started • ${state.clockSetting===10?'10-second stress test':state.clockSetting+' second clock'}`)}
function resetDraft(){state={...state,started:false,paused:true,round:0,pickIndex:0,remaining:state.clockSetting,deadline:null,target:null,broadcastReveal:null,privateReveals:{},reserved:{},reserveMeta:{},drafted:{},captainTeam:null};state.teams.forEach(t=>t.roster=[]);render();toast('Draft reset.')}
function finishPick(){state.target=null;state.broadcastReveal=null;state.privateReveals={};const ord=order();state.pickIndex++;if(state.pickIndex>=ord.length){state.round++;state.pickIndex=0}state.remaining=state.clockSetting;state.deadline=state.started?Date.now()+state.clockSetting*1000:null;state.paused=false;render()}
function draftCurrent(){if(!state.started)return toast('Draft has not started.');if(!authorizedToDraft())return toast('Only the current captain or Admin can draft.');const pid=state.target;if(!pid)return toast('Select a player first.');if(!allAvailable().some(p=>p.id===pid))return toast('That player is unavailable.');const t=currentTeam();if(t.roster.length>=6)return toast('Roster is full.');t.roster.push(pid);state.drafted[t.id]=t.roster.slice();finishPick();toast(`${player(pid).name} drafted to ${t.name}.`)}
function reserveCurrent(){if(!state.started)return toast('Draft has not started.');if(state.round<1)return toast('PLAYER RESERVE unlocks after Round 1.');if(!authorizedToDraft())return toast('Only the current captain or Admin can reserve.');const pid=state.target;if(!pid)return toast('Reveal/select a player first.');if(!allAvailable().some(p=>p.id===pid))return toast('That player is unavailable.');const tid=currentTeamId();if(state.reserved[pid])return toast('That player is already reserved.');state.reserved[pid]=tid;state.reserveMeta[tid]={playerId:pid,skipRound:state.round+1,compRound:state.round+2};render();toast(`${player(pid).name} reserved for ${tname(tid)}. Make your normal pick.`)}
function tname(id){return team(id)?.name||`TEAM ${String(id).padStart(2,'0')}`}
function revealBroadcast(){if(!state.target)return toast('No live target.');state.broadcastReveal=state.target;render()}
function privateReveal(pid){if(!state.captainTeam)return;if(!allAvailable().some(p=>p.id===pid))return;state.privateReveals[state.captainTeam]=pid;render()}
function reserveDecision(){const tid=currentTeamId(),m=state.reserveMeta[tid];if(!state.started||!m||m.compRound!==state.round||document.getElementById('modalBack'))return;const p=player(m.playerId);openModal(`<div class="eyebrow">COMPENSATION PICK</div><h3>${team(tid).name}</h3><p class="sub">Your reserved player is protected. Choose what happens before this pick.</p><div class="reserveBox"><strong>${p.id} • ${p.name}</strong><div style="margin-top:4px;color:#b7aebe">${p.role}</div></div><div class="modalActions"><button class="btn good" id="take">TAKE RESERVED</button><button class="btn warn" id="keep">KEEP RESERVED + PICK</button><button class="btn danger" id="forfeit">FORFEIT + PICK</button></div>`);$('#take').onclick=()=>{const t=team(tid);if(t.roster.length>=6)return toast('Roster full.');t.roster.push(p.id);state.drafted[tid]=t.roster.slice();delete state.reserved[p.id];delete state.reserveMeta[tid];closeModal();finishPick();toast(`${p.name} claimed from reserve.`)};$('#keep').onclick=()=>{closeModal();toast('Reserve protected. Choose another player.');render()};$('#forfeit').onclick=()=>{delete state.reserved[p.id];delete state.reserveMeta[tid];closeModal();toast('Reserve forfeited. Choose another player.');render()}}
function updateClockUI(){document.querySelectorAll('[data-clock]').forEach(el=>el.textContent=fmt(state.remaining));document.querySelectorAll('[data-clockbar]').forEach(el=>el.style.width=`${Math.max(0,Math.min(100,state.remaining/state.clockSetting*100))}%`)}
function renderCard(show,src){return `<div class="deck ${show?'revealed':''}"><div class="deckInner"><div class="face back"><img src="assets/card-back.svg" alt="THE SIX card back"></div><div class="face front"><img src="${src||'cards/P001.svg'}" alt="Player card"></div></div></div>`}
function renderTop(){return `<header class="top"><div class="brand"><div class="brandMark"><b>✦</b></div><div class="brandText"><strong>THE SIX</strong><span>GOD SYNDICATE • DRAFT COMMAND</span></div></div><div class="topActions"><button class="btn ghost" id="broadcastNav">BROADCAST</button>${state.adminAuthed?`<button class="btn" id="adminNav">ADMIN CONTROL</button>`:`<button class="btn" id="adminAccess">ADMIN ACCESS</button>`}${state.captainTeam?`<button class="btn" id="captainNav">CAPTAIN CONTROL</button><button class="btn danger" id="logout">LOG OUT</button>`:`<button class="btn" id="captainAccess">CAPTAIN LOGIN</button>`}</div></header>`}
function renderBroadcast(){const t=currentTeam(),tar=state.target?player(state.target):null,reveal=state.broadcastReveal?player(state.broadcastReveal):null;return `<section class="panel mainStage"><div class="stageGlow"></div><div class="stageTop"><div class="turnInfo"><small>ROUND ${state.round+1} • PICK ${state.pickIndex+1}</small><strong>${state.started?`${t.name} — ON THE CLOCK`:'DRAFT STANDBY'}</strong></div><div class="currentTarget"><div class="targetLabel">CURRENT CAPTAIN</div><div class="targetName">${t.captain}</div><div class="targetLabel" style="margin-top:7px">CURRENT TARGET</div><div>${tar?`${tar.id} • ${tar.name}`:'No player selected'}</div></div></div><div class="deckWrap" id="broadcastDeck">${renderCard(!!reveal,reveal?.card)}</div><div class="stageActions"><button class="btn primary" id="revealBroadcast">${reveal?'PLAYER REVEALED':'REVEAL TARGET'}</button></div><div class="notice" style="margin:0 18px 18px">Broadcast is read-only. Admin and captain controls are private. The live target is visible, but only an authenticated current captain or Admin can actually draft.</div></section>`}
function renderPool(privateMode){const privatePid=state.privateReveals[state.captainTeam];const list=allAvailable().filter(p=>state.filter==='ALL'||p.role===state.filter);return `<section class="panel pool"><div class="panelHead"><div><h2>${privateMode?'PRIVATE SCOUTING POOL':'LIVE PLAYER POOL'}</h2><div class="eyebrow">${privateMode?'CARDS FACE-DOWN BY DEFAULT':'AVAILABLE PLAYERS'}</div></div><span class="badge">${list.length} AVAILABLE</span></div><div class="panelBody"><div class="filters">${ROLES.map(r=>`<button class="filter ${state.filter===r?'active':''}" data-filter="${r}">${r}</button>`).join('')}</div><div class="playerGrid">${list.map(p=>{const selected=state.target===p.id;const show=privateMode&&privatePid===p.id;const locked=!!state.reserved[p.id];return `<button class="playerCard ${selected?'selected':''} ${locked?'locked':''}" data-player="${p.id}"><img src="${show?p.card:'assets/card-back.svg'}" alt="${show?p.name:'Face-down card'}"><span class="label">${p.id} • ${p.name}</span></button>`}).join('')}</div></div></section>`}
function renderOrder(){return `<section class="panel"><div class="panelHead"><h2>TURN ORDER</h2><span class="badge">${state.teamsCount} TEAMS</span></div><div class="panelBody"><div class="orderList">${order().map((tid,i)=>`<div class="orderItem ${i===state.pickIndex?'current':''}"><div><strong>${i+1}. ${team(tid).name}</strong><div style="margin-top:3px;color:#aaa0b0;font-size:11px">${team(tid).captain}</div></div><small>${i===state.pickIndex?'ON THE CLOCK':'UP NEXT'}</small></div>`).join('')}</div></div></section>`}
function renderRosters(){return `<section class="panel"><div class="panelHead"><h2>TEAM ROSTERS</h2><span class="badge">${state.teamsCount} ACTIVE</span></div>${activeTeams().map(t=>`<div class="rosterBoard"><div class="teamRoster"><img src="assets/team-card-reference.svg" alt="Team roster reference"><div class="teamOverlay"><div class="teamTitle">${t.name}</div><div class="captainName">${t.captain}</div>${(t.roster||[]).slice(0,5).map((pid,i)=>`<div class="slot s${i+1}"><img src="${player(pid).card}" alt="${player(pid).name}"><span class="slotLabel">${player(pid).name}</span></div>`).join('')}<div class="slot captain"><div class="slotLabel">SLOT 06<br>${t.captain}</div></div></div></div></div>`).join('')}</section>`}
function renderAdmin(){return `<section class="panel"><div class="panelHead"><div><h2>ADMIN CONTROL</h2><div class="eyebrow">PRIVATE COMMAND CENTER • ACCESS GRANTED</div></div><span class="badge">1290 UNLOCKED</span></div><div class="panelBody"><div class="settingsGrid"><div class="field"><label>TEAM COUNT</label><select id="teamCount" class="select">${[4,5,6].map(n=>`<option value="${n}" ${state.teamsCount===n?'selected':''}>${n} TEAMS</option>`).join('')}</select></div><div class="field"><label>DRAFT CLOCK</label><select id="clockSetting" class="select">${[10,30,60,90].map(n=>`<option value="${n}" ${state.clockSetting===n?'selected':''}>${n===10?'10 SEC STRESS TEST':n+' SECONDS'}</option>`).join('')}</select></div></div><div class="stageActions" style="justify-content:flex-start;padding-left:0;padding-right:0"><button class="btn primary" id="start">${state.started?'RESTART DRAFT':'START DRAFT'}</button><button class="btn" id="pause">${state.paused?'RESUME CLOCK':'PAUSE CLOCK'}</button><button class="btn danger" id="reset">RESET DRAFT</button></div><div class="notice">Admin is the only place with host controls. Captains cannot draft another team’s picks and the broadcast is read-only.</div></div></section>`}
function renderCaptain(){const tid=state.captainTeam,t=team(tid),myTurn=currentTeamId()===tid,privatePid=state.privateReveals[tid],privateP=privatePid?player(privatePid):null;return `<section class="panel"><div class="panelHead"><div><h2>CAPTAIN CONTROL</h2><div class="eyebrow">TEAM ${String(tid).padStart(2,'0')} • PRIVATE SCOUTING</div></div><span class="badge">${myTurn?'ON THE CLOCK':'SCOUTING'}</span></div><div class="panelBody"><div class="settingsGrid"><div class="field"><label>TEAM NAME</label><input id="teamName" class="input" value="${t.name}"></div><div class="field"><label>CAPTAIN NAME</label><input id="captainName" class="input" value="${t.captain}"></div></div><div class="stageActions" style="justify-content:flex-start;padding-left:0;padding-right:0"><button class="btn primary" id="saveProfile">SAVE TEAM PROFILE</button></div><div class="notice">${myTurn?'You are on the clock. Hovering/selecting a player targets them for the broadcast, but your card stays face-down until you reveal it.':'You are scouting. Every available card is face-down. Click a card to privately reveal it for your team only.'}</div><div style="display:grid;grid-template-columns:270px minmax(0,1fr);gap:18px;margin-top:18px"><div><div class="eyebrow">PRIVATE REVEAL</div>${renderCard(!!privateP,privateP?.card)}<div class="stageActions" style="padding-left:0;padding-right:0;justify-content:flex-start"><button class="btn primary" id="revealPrivate">${privateP?'REVEALED':'REVEAL CARD'}</button>${myTurn?`<button class="btn good" id="draftCaptain" ${privateP?'':'disabled'}>DRAFT PLAYER</button><button class="btn warn" id="reserveCaptain" ${privateP&&state.round>0?'':'disabled'}>PLAYER RESERVE</button>`:''}</div></div><div>${renderPool(true)}</div></div></div></section>`}
function render(){app.innerHTML=`<div class="noise"></div><div class="app">${renderTop()}<div class="wrap"><section class="hero"><div><div class="heroTag">GOD SYNDICATE PRESENTS</div><h1>THE <span>SIX</span></h1><p>YOU DON'T CHOOSE YOUR TEAM. YOU GET DRAFTED.</p></div><div class="heroRight"><div class="heroPanel"><div class="eyebrow">${state.started?'LIVE DRAFT':'DRAFT STANDBY'}</div><div class="clock"><div><small>CURRENT CAPTAIN</small><div style="font-family:'Barlow Condensed';font-size:30px">${currentTeam().name}</div><div style="color:#a99eb0;font-size:12px">${currentTeam().captain}</div></div><div style="text-align:right"><small>TIME REMAINING</small><strong data-clock>${fmt(state.remaining)}</strong></div></div></div></div></section><div class="grid"><div>${state.mode==='admin'?renderAdmin():state.mode==='captain'?renderCaptain():renderBroadcast()}${state.mode==='broadcast'?renderPool(false):''}</div><aside class="rail">${renderOrder()}${renderRosters()}</aside></div></div></div>`;bind();updateClockUI();reserveDecision()}
function bind(){document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});document.querySelectorAll('[data-player]').forEach(b=>{b.onclick=()=>{const pid=b.dataset.player;if(state.mode==='captain')privateReveal(pid);else{state.target=pid;state.broadcastReveal=null;render()}}});$('#adminAccess')?.addEventListener('click',openAdminAuth);$('#adminNav')?.addEventListener('click',()=>{state.mode='admin';render()});$('#captainAccess')?.addEventListener('click',openCaptainLogin);$('#captainNav')?.addEventListener('click',()=>{state.mode='captain';render()});$('#broadcastNav')?.addEventListener('click',()=>{state.mode='broadcast';render()});$('#logout')?.addEventListener('click',()=>{state.captainTeam=null;state.mode='broadcast';render()});$('#start')?.addEventListener('click',startDraft);$('#pause')?.addEventListener('click',()=>{state.paused=!state.paused;if(!state.paused&&state.started)state.deadline=Date.now()+state.remaining*1000;render()});$('#reset')?.addEventListener('click',resetDraft);$('#teamCount')?.addEventListener('change',e=>{state.teamsCount=Number(e.target.value);resetDraft()});$('#clockSetting')?.addEventListener('change',e=>{state.clockSetting=Number(e.target.value);if(!state.started)state.remaining=state.clockSetting;render()});$('#saveProfile')?.addEventListener('click',()=>{const t=team(state.captainTeam);t.name=$('#teamName').value.trim()||t.name;t.captain=$('#captainName').value.trim()||t.captain;render();toast('Team profile saved.')});$('#revealPrivate')?.addEventListener('click',()=>{const pid=state.privateReveals[state.captainTeam]||allAvailable()[0]?.id;if(pid)privateReveal(pid)});$('#draftCaptain')?.addEventListener('click',draftCurrent);$('#reserveCaptain')?.addEventListener('click',reserveCurrent);$('#revealBroadcast')?.addEventListener('click',revealBroadcast)}
setInterval(()=>{if(!state.started||state.paused||!state.deadline)return;const left=Math.max(0,Math.ceil((state.deadline-Date.now())/1000));if(left!==state.remaining){state.remaining=left;updateClockUI()}if(left===0){finishPick();toast('TIME EXPIRED — ADVANCING TURN')}},200);
render();