(function(){
const REAL_BACK='assets/card-back-live.svg';
const REAL_P001='cards/P001-live.svg';
function safeRender(){try{if(typeof window.render==='function')window.render()}catch(e){console.error(e)}}
function imgForPlayer(p){return p?.id==='P001'?REAL_P001:'assets/player-placeholder.svg'}
function cardBack(){return REAL_BACK}
window.renderCard=function(show,src){const actual=(src&&src.includes('P001'))?REAL_P001:(src||REAL_P001);return `<div class="deck ${show?'revealed':''}"><div class="deckInner"><div class="face back"><img src="${cardBack()}" alt="THE SIX card back"></div><div class="face front"><img src="${actual}" alt="Player card"></div></div></div>`};
window.adjustClock=function(delta){state.clockSetting=Math.max(10,Math.min(180,(Number(state.clockSetting)||60)+delta));if(state.started){state.remaining=Math.max(10,Math.min(state.clockSetting,state.remaining+delta));state.deadline=state.paused?null:Date.now()+state.remaining*1000}safeRender();toast(`CLOCK ${fmt(state.remaining)}`)};
window.startDraft=function(){if(!state.adminAuthed||state.mode!=='admin')return toast('Unlock Admin Control first.');state.clockSetting=Math.max(10,Math.min(180,Number(state.clockSetting)||60));state.started=true;state.paused=false;state.round=0;state.turnIndex=0;state.target=null;state.broadcastReveal=null;state.privateReveals={};state.reserved={};state.reserveMeta={};state.drafted={};state.teams.forEach(t=>t.roster=[]);state.remaining=state.clockSetting;state.deadline=Date.now()+state.clockSetting*1000;safeRender();toast(`DRAFT STARTED • ${fmt(state.remaining)}`)};
window.renderAdmin=function(){return `<section class="panel adminPanel premiumAdmin"><div class="panelhead"><div><h2>ADMIN CONTROL</h2><div class="eyebrow">PRIVATE COMMAND CENTER • 1290 VERIFIED</div></div><span class="badge">HOST</span></div><div class="adminHero"><div><span>ACTIVE CLOCK</span><strong data-clock>${fmt(state.remaining)}</strong><small>${state.started?(state.paused?'PAUSED':'LIVE'):'STANDBY'} • ${state.clockSetting}s base</small></div><div class="adminClockButtons"><button class="btn" id="minus5">−5 SEC</button><button class="btn primary" id="start">${state.started?'RESTART DRAFT':'START DRAFT'}</button><button class="btn" id="plus5">+5 SEC</button></div></div><div class="adminRow"><button class="btn" id="pause">${state.paused?'RESUME CLOCK':'PAUSE CLOCK'}</button><button class="btn" id="force">FORCE NEXT</button><button class="btn danger" id="reset">RESET DRAFT</button></div><div class="adminHint"><b>Stress test:</b> use −5 SEC until the clock reaches 10 seconds. Live event baseline is 60 seconds.</div></section>`};
window.renderRosters=function(){return `<section class="rosterSection"><div class="sectionTitleRow"><div><div class="eyebrow">LIVE TEAM BOARD</div><h2>TEAM ROSTERS</h2></div><span>${state.teamsCount} ACTIVE</span></div>${activeTeams().map(t=>{const slots=t.roster||[];return `<article class="proRoster"><div class="proRosterTop"><div><div class="proTeamCode">TEAM ${String(t.id).padStart(2,'0')}</div><div class="proTeamName">${t.name}</div><div class="proCaptain">CAPTAIN • ${t.captain}</div></div><div class="proCrest">✦</div></div><div class="proRosterGrid"><div class="proSlot captainSlot"><div class="slotNumber">06</div><div class="slotImage captainIcon">C</div><div class="slotText"><b>${t.captain}</b><span>CAPTAIN</span></div></div>${Array.from({length:5},(_,i)=>{const p=slots[i]?player(slots[i]):null;return `<div class="proSlot"><div class="slotNumber">0${i+1}</div><div class="slotImage">${p?`<img src="${imgForPlayer(p)}" alt="${p.name}">`:'<span>+</span>'}</div><div class="slotText"><b>${p?p.name:'OPEN SLOT'}</b><span>${p?p.role:'WAITING TO BE DRAFTED'}</span></div></div>`}).join('')}</div></article>`}).join('')}</section>`};
window.renderPool=function(privateMode){const privatePid=state.privateReveals?.[state.captainTeam];const list=availablePlayers().filter(p=>state.filter==='ALL'||p.role===state.filter);return `<section class="panel poolPanel"><div class="panelhead"><div><h2>${privateMode?'PRIVATE SCOUTING POOL':'LIVE PLAYER POOL'}</h2><div class="eyebrow">${privateMode?'FACE-DOWN UNTIL YOU REVEAL':'AVAILABLE PLAYERS'}</div></div><span class="badge">${list.length} AVAILABLE</span></div><div class="filters">${ROLES.map(r=>`<button class="filter ${state.filter===r?'active':''}" data-filter="${r}">${r}</button>`).join('')}</div><div class="playerGrid">${list.map(p=>{const show=privateMode&&privatePid===p.id;return `<button class="playerCard ${state.target===p.id?'selected':''}" data-player="${p.id}"><img src="${show?imgForPlayer(p):cardBack()}" alt="${show?p.name:'Face-down card'}"><span>${p.number} • ${p.name}</span><small>${p.role}</small></button>`}).join('')}</div></section>`};
const originalRender=window.render;
window.render=function(){originalRender();setTimeout(bindPatch,0)};
function bindPatch(){const a=document.getElementById('minus5');if(a)a.onclick=()=>adjustClock(-5);const b=document.getElementById('plus5');if(b)b.onclick=()=>adjustClock(5);const st=document.getElementById('start');if(st)st.onclick=()=>startDraft();const pa=document.getElementById('pause');if(pa)pa.onclick=()=>{state.paused=!state.paused;if(!state.paused&&state.started)state.deadline=Date.now()+state.remaining*1000;else state.deadline=null;safeRender()};const force=document.getElementById('force');if(force)force.onclick=()=>moveNext();const reset=document.getElementById('reset');if(reset)reset.onclick=()=>resetDraft();document.querySelectorAll('.proRoster img,.playerCard img,.face img').forEach(el=>{if(el.getAttribute('src')==='assets/card-back.svg')el.src=REAL_BACK;if(el.getAttribute('src')==='cards/P001.svg')el.src=REAL_P001})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindPatch);else bindPatch();
})();