(function(){
const REAL_BACK='assets/card-back-live.svg';
const REAL_P001='cards/P001-live.svg';
const PLACEHOLDER='cards/player-placeholder.svg';
function realCardSrc(pid){return pid==='P001'?REAL_P001:PLACEHOLDER}
function fixImages(){document.querySelectorAll('img').forEach(img=>{const s=img.getAttribute('src')||'';if(s==='assets/card-back.svg'||s.endsWith('/assets/card-back.svg'))img.setAttribute('src',REAL_BACK);if(s==='cards/P001.svg'||s.endsWith('/cards/P001.svg'))img.setAttribute('src',REAL_P001)})}
function buildRosterCard(t){const roster=t.roster||[];const playerById=(id)=>{try{return typeof player==='function'?player(id):null}catch(e){return null}};const slots=Array.from({length:5},(_,i)=>{const p=roster[i]?playerById(roster[i]):null;return `<div class="six-slot ${p?'':'six-roster-empty'}"><span class="six-slot-num">0${i+1}</span><div class="six-slot-img">${p?`<img src="${realCardSrc(p.id)}" alt="${p.name}">`:'<div class="six-slot-empty">+</div>'}</div><div class="six-slot-name">${p?p.name:'OPEN SLOT'}</div><div class="six-slot-role">${p?p.role:'Waiting to be drafted'}</div></div>`});return `<article class="six-team-card"><div class="six-team-top"><div class="six-team-identity"><div class="six-team-crest">✦</div><div><div class="six-team-code">TEAM ${String(t.id).padStart(2,'0')}</div><div class="six-team-name">${t.name}</div><div class="six-team-captain">CAPTAIN • ${t.captain}</div></div></div><div class="six-team-status">6 SLOTS • LIVE ROSTER</div></div><div class="six-team-slots"><div class="six-slot captain"><span class="six-slot-num">06</span><div class="six-slot-img"><div class="six-slot-empty" style="color:#c88cff">C</div></div><div class="six-slot-name">${t.captain}</div><div class="six-slot-role">Captain</div></div>${slots.join('')}</div></article>`}
function rewriteRosters(){document.querySelectorAll('.rosterBoard').forEach(node=>{const idText=node.querySelector('.teamTitle')?.textContent||'';const idMatch=idText.match(/TEAM\s*(\d+)/i);if(!idMatch)return;const tid=Number(idMatch[1]);const t=typeof team==='function'?team(tid):null;if(!t)return;const fresh=document.createElement('div');fresh.innerHTML=buildRosterCard(t);node.replaceWith(fresh.firstElementChild)});document.querySelectorAll('.proRoster').forEach(node=>{const code=node.querySelector('.proTeamCode')?.textContent||'';const m=code.match(/TEAM\s*(\d+)/i);if(!m)return;const t=typeof team==='function'?team(Number(m[1])):null;if(!t)return;const fresh=document.createElement('div');fresh.innerHTML=buildRosterCard(t);node.replaceWith(fresh.firstElementChild)})}
function refresh(){fixImages();rewriteRosters()}
const obs=new MutationObserver(()=>requestAnimationFrame(refresh));obs.observe(document.documentElement,{childList:true,subtree:true});
setInterval(refresh,1200);requestAnimationFrame(refresh);
})();